version: "3.5"

services:
  mongodb:
    container_name: mongodb
    image: mongo:5.0.10
    restart: always
    # To secure MongoDB, uncomment and set the following values
    # environment:
    #   - MONGO_INITDB_DATABASE=admin
    #   - MONGO_INITDB_ROOT_USERNAME=admin
    #   - MONGO_INITDB_ROOT_PASSWORD=changeme
    volumes:
      - llmware-mongodb:/data/db
    ports:
      - '27017:27017'

volumes:
    llmware-mongodb:
      driver: local


